version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    ports:
      - "5000:5000"
  app2:
    build: ./flask-jinja-tutorial/flask_jinja_tutorial
    container_name: "Flask_App_2"
    ports:
      - "5001:5001"
  app3:
    build: ./flask-wtforms-tutorial/flask_wtforms_tutorial
    container_name: "Flask_App_3"
    ports:
      - "5002:5002"
  app4:
    build: ./app4
    container_name: "Flask_App_4"
    ports:
      - "5003:5003"
  app5:
    build: ./app5
    container_name: "Flask_App_5"
    ports:
      - "5004:5004"
  app6:
    build: ./app6
    container_name: "Flask_App_6"
    ports:
      - "5005:5005"
  app7:
    build: ./flask-blueprint-tutorial/flask_blueprint_tutorial
    container_name: "Flask_App_7"
    ports:
      - "5006:5006"
  app8:
    build: ./flask-assets-tutorial/flask_assets_tutorial
    container_name: "Flask_App_8"
    ports:
      - "5007:5007"
  app9:
    build: ./flask-sqlalchemy-tutorial/application
    container_name: "Flask_App_9"
    ports:
      - "5008:5008"